import express from 'express';import cors from 'cors';import dotenv from 'dotenv';import mongoose from 'mongoose';import bcrypt from 'bcryptjs';import jwt from 'jsonwebtoken';dotenv.config();
const app=express(),secret=process.env.JWT_SECRET||'dev-secret';app.use(cors());app.use(express.json());app.use(express.static('public'));app.get('/admin',(q,s)=>s.sendFile(process.cwd()+'/public/admin.html'));
const User=mongoose.model('User',new mongoose.Schema({name:String,email:{type:String,unique:true},phone:String,password:String,role:{type:String,enum:['farmer','fpo','buyer','admin']},approvalStatus:{type:String,default:'pending'},createdAt:{type:Date,default:Date.now}}));
const Lot=mongoose.model('Lot',new mongoose.Schema({ownerId:mongoose.Schema.Types.ObjectId,crop:String,grade:String,quantity:Number,region:String,expectedPrice:Number,status:{type:String,default:'Open'},createdAt:{type:Date,default:Date.now}}));
const Offer=mongoose.model('Offer',new mongoose.Schema({lotId:mongoose.Schema.Types.ObjectId,buyerId:mongoose.Schema.Types.ObjectId,price:Number,status:{type:String,default:'Pending'},createdAt:{type:Date,default:Date.now}}));
const Order=mongoose.model('Order',new mongoose.Schema({lotId:mongoose.Schema.Types.ObjectId,offerId:mongoose.Schema.Types.ObjectId,status:{type:String,default:'Pending'},paymentStatus:{type:String,default:'Pending'},createdAt:{type:Date,default:Date.now}}));
const auth=(req,res,next)=>{try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);next()}catch{res.status(401).json({error:'Authentication required'})}};const admin=(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({error:'Admin access required'});
app.get('/api/health',(q,s)=>s.json({ok:true,name:'AgriLink API',database:mongoose.connection.readyState===1?'connected':'disconnected'}));
app.post('/api/auth/register',async(req,res)=>{try{const {name,email,password,phone='',role='farmer'}=req.body;if(!name||!email||!password||!['farmer','fpo','buyer'].includes(role))return res.status(400).json({error:'Invalid registration details'});const u=await User.create({name,email:email.toLowerCase(),phone,password:await bcrypt.hash(password,10),role});res.status(201).json({message:'Registration submitted for admin approval',user:{id:u._id,name:u.name,role:u.role,approvalStatus:u.approvalStatus}})}catch(e){res.status(409).json({error:e.code===11000?'Email already registered':'Registration failed'})}});
app.post('/api/auth/login',async(req,res)=>{const u=await User.findOne({email:String(req.body.email||'').toLowerCase()});if(!u||!(await bcrypt.compare(req.body.password||'',u.password)))return res.status(401).json({error:'Invalid email or password'});if(u.role!=='admin'&&u.approvalStatus!=='approved')return res.status(403).json({error:`Account is ${u.approvalStatus}`});res.json({token:jwt.sign({id:u._id,role:u.role},secret),user:{id:u._id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/admin/users',auth,admin,async(q,s)=>s.json(await User.find().select('-password')));app.patch('/api/admin/users/:id/status',auth,admin,async(req,s)=>{const u=await User.findByIdAndUpdate(req.params.id,{approvalStatus:req.body.approvalStatus},{new:true}).select('-password');u?s.json(u):s.status(404).json({error:'User not found'})});
app.get('/api/lots',async(q,s)=>s.json(await Lot.find()));app.post('/api/lots',auth,async(req,s)=>s.status(201).json(await Lot.create({...req.body,ownerId:req.user.id})));app.get('/api/offers',auth,async(req,s)=>s.json(await Offer.find({buyerId:req.user.id})));app.post('/api/offers',auth,async(req,s)=>s.status(201).json(await Offer.create({...req.body,buyerId:req.user.id})));app.get('/api/orders',auth,async(q,s)=>s.json(await Order.find()));
async function seedAdmin(){if(!process.env.ADMIN_EMAIL||!process.env.ADMIN_PASSWORD)return;const email=process.env.ADMIN_EMAIL.toLowerCase();await User.findOneAndUpdate({email},{name:'Owner',email,password:await bcrypt.hash(process.env.ADMIN_PASSWORD,10),role:'admin',approvalStatus:'approved'},{upsert:true,new:true,setDefaultsOnInsert:true});}
mongoose.connect(process.env.MONGODB_URI).then(async()=>{await seedAdmin();app.listen(process.env.PORT||5000,()=>console.log('AgriLink API running'))}).catch(e=>{console.error(e.message);process.exit(1)});
