import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
dotenv.config();
const app=express();const port=process.env.PORT||5000;const secret=process.env.JWT_SECRET||'dev-secret';
app.use(cors());app.use(express.json());
const users=[];const lots=[];const offers=[];const orders=[];
const prices=[{crop:'Paddy',region:'Thanjavur',price:2340,change:4.2},{crop:'Onion',region:'Lasalgaon',price:1980,change:2.8},{crop:'Tomato',region:'Kolar',price:1560,change:-1.1}];
const schemes=[{id:'pm-kisan',name:'PM-KISAN Samman Nidhi',description:'Income support for eligible farmer families.',status:'You may qualify'}];
const equipment=[{id:'tractor-575',name:'Mahindra 575 DI Tractor',region:'Thanjavur',rate:1200,unit:'day',status:'Available today'}];
const tokenFor=user=>jwt.sign({id:user.id,role:user.role},secret,{expiresIn:'7d'});
const auth=(req,res,next)=>{try{const value=(req.headers.authorization||'').replace('Bearer ','');req.user=jwt.verify(value,secret);next()}catch{res.status(401).json({error:'Authentication required'})}};
app.get('/api/health',(req,res)=>res.json({ok:true,name:'AgriLink API'}));
app.post('/api/auth/register',async(req,res)=>{const {name,email,password,role='farmer',phone=''}=req.body;if(!name||!email||!password||!['farmer','fpo','buyer'].includes(role))return res.status(400).json({error:'Valid name, email, password and role are required'});if(users.some(u=>u.email===email.toLowerCase()))return res.status(409).json({error:'Email already registered'});const user={id:crypto.randomUUID(),name,email:email.toLowerCase(),phone,password:await bcrypt.hash(password,10),role,approvalStatus:'pending',createdAt:new Date().toISOString()};users.push(user);res.status(201).json({message:'Registration submitted for admin approval',user:{id:user.id,name:user.name,email:user.email,role:user.role,approvalStatus:user.approvalStatus}})});
app.post('/api/auth/login',async(req,res)=>{const user=users.find(u=>u.email===String(req.body.email||'').toLowerCase());if(!user||!(await bcrypt.compare(req.body.password||'',user.password)))return res.status(401).json({error:'Invalid email or password'});if(user.approvalStatus!=='approved')return res.status(403).json({error:`Account is ${user.approvalStatus}. Please wait for admin approval.`});res.json({token:tokenFor(user),user:{id:user.id,name:user.name,email:user.email,role:user.role}})});
app.get('/api/admin/users',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required'});res.json(users.map(({password,...user})=>user))});
app.patch('/api/admin/users/:id/status',auth,(req,res)=>{if(req.user.role!=='admin')return res.status(403).json({error:'Admin access required'});const user=users.find(u=>u.id===req.params.id);if(!user||!['pending','approved','rejected','suspended'].includes(req.body.approvalStatus))return res.status(400).json({error:'Invalid user or status'});user.approvalStatus=req.body.approvalStatus;const {password,...safe}=user;res.json(safe)});
app.get('/api/market/prices',(req,res)=>res.json(prices));app.get('/api/schemes',(req,res)=>res.json(schemes));app.get('/api/equipment',(req,res)=>res.json(equipment));
app.get('/api/lots',(req,res)=>res.json(lots.map(({ownerId,...lot})=>lot)));app.post('/api/lots',auth,(req,res)=>{const lot={id:crypto.randomUUID(),ownerId:req.user.id,crop:req.body.crop||'Paddy',grade:req.body.grade||'Grade A',quantity:Number(req.body.quantity)||0,region:req.body.region||'',expectedPrice:Number(req.body.expectedPrice)||0,status:'Open',createdAt:new Date().toISOString()};lots.push(lot);res.status(201).json(lot)});
app.post('/api/offers',auth,(req,res)=>{const lot=lots.find(l=>l.id===req.body.lotId);if(!lot)return res.status(404).json({error:'Crop lot not found'});const offer={id:crypto.randomUUID(),lotId:lot.id,buyerId:req.user.id,price:Number(req.body.price)||0,status:'Pending',createdAt:new Date().toISOString()};offers.push(offer);res.status(201).json(offer)});
app.get('/api/offers',auth,(req,res)=>res.json(offers.filter(o=>req.user.role==='admin'||o.buyerId===req.user.id||lots.find(l=>l.id===o.lotId)?.ownerId===req.user.id)));
app.patch('/api/offers/:id',auth,(req,res)=>{const offer=offers.find(o=>o.id===req.params.id);if(!offer)return res.status(404).json({error:'Offer not found'});offer.status=req.body.status||offer.status;if(offer.status==='Accepted'){const lot=lots.find(l=>l.id===offer.lotId);lot.status='Sold';orders.push({id:crypto.randomUUID(),lotId:lot.id,offerId:offer.id,status:'Transport assigned',paymentStatus:'Pending',createdAt:new Date().toISOString()})}res.json(offer)});
app.get('/api/orders',auth,(req,res)=>res.json(orders));app.patch('/api/orders/:id',auth,(req,res)=>{const order=orders.find(o=>o.id===req.params.id);if(!order)return res.status(404).json({error:'Order not found'});Object.assign(order,req.body);res.json(order)});
app.listen(port,()=>console.log(`AgriLink API running on ${port}`));
